{
 "title": "K8S - Namespace and Pods",
 "tags": [
  "prometheus",
  "k8s"
 ],
 "time": { "from": "2021-02-08T12:06:25.386Z", "to": "2021-02-10T12:06:25.386Z" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_node_created, kubernetes_cluster_name)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels{kubernetes_cluster_name=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_owner{kubernetes_cluster_name=\"$cluster\",namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Namespace - Quotas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\"}) by (namespace)\n",
     "group": { "filter": "$cluster" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Used",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "kube_resourcequota{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",resource=\"requests.cpu\",type=\"hard\"}",
     "group": { "filter": "$cluster" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Quota",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",container_name=\"\"}[10m]))",
     "legendFormat": "Real"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\"}) by (namespace)",
     "group": { "filter": "$cluster" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Used",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "kube_resourcequota{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",resource=\"limits.cpu\",type=\"hard\"}",
     "group": { "filter": "$cluster" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Quota",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",container_name=\"\"}[10m]))",
     "legendFormat": "Real"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\"}) by (namespace)",
     "group": { "filter": "$cluster" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Used",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "kube_resourcequota{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",resource=\"requests.memory\",type=\"hard\"}",
     "group": { "filter": "$cluster" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Quota",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(container_memory_working_set_bytes{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",container_name=\"\"})\n",
     "legendFormat": "Real"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\"}) by (namespace)",
     "group": { "filter": "$cluster" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Used",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "kube_resourcequota{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",resource=\"limits.memory\",type=\"hard\"}",
     "group": { "filter": "$cluster" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Quota",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(container_memory_working_set_bytes{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",container_name=\"\"})\n",
     "legendFormat": "Real"
    }
   ]
  },
  {
   "title": "Pods usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_status_phase{kubernetes_cluster_name=\"$cluster\", namespace=\"$namespace\"})",
     "group": { "filter": "$cluster" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Used",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "kube_resourcequota{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",resource=\"pods\",type=\"hard\"}",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "PVC usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_persistentvolumeclaim_status_phase{kubernetes_cluster_name=\"$cluster\", namespace=\"$namespace\"}) by (namespace)\r",
     "group": { "filter": "$cluster" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Used",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "kube_resourcequota{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",resource=\"persistentvolumeclaims\",type=\"hard\"}",
     "legendFormat": "Quota"
    }
   ]
  },
  { "title": "Namespace - Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pods by phase",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_status_phase{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\"}) by (phase)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{phase}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Pod containers by waiting reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_status_waiting_reason{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\"}) by (reason)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{reason}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Pod container termination reason",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_container_status_terminated_reason{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\"}) by (reason)\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{reason}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Pod distribution by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(kube_pod_info{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\"}) by (node)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{node}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Pod - Generic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU requests",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 38 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}) by (pod)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "CPU limits",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 38 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}) by (pod)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "CPU real",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 38 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(container_cpu_usage_seconds_total{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\", pod=\"$pod\",container=\"\"}[10m])\n",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Mem requests",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 38 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}) by (pod)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Mem limits",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 38 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}) by (pod)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Mem real",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 38 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(container_memory_working_set_bytes{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container=\"\"})",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  { "title": "Pod - CPU and Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(irate(container_cpu_usage_seconds_total{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",container!=\"POD\",container!=\"\"}[10m])) by (container)\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$pod - {{container}} - used",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{kubernetes_cluster_name=\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "$pod - {{container}} - limit"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{kubernetes_cluster_name=\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod Mem usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$pod\",container!=\"POD\",container!=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "$pod - {{container}} - used",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{kubernetes_cluster_name=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "$pod - {{container}} - limit"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{kubernetes_cluster_name=\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  { "title": "Pod - Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Network receive bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[10m])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network transmit bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[10m])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Pod - Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Disk read bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[10m])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Disk write bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[10m])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}